# Generated by Django 4.1.7 on 2023-06-11 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('GROUP_ADDED', 'Group Added'), ('GROUP_REMOVED', 'Group Removed'), ('STATUS_CHANGED', 'Status Changed'), ('TASK_DELETED', 'Task Deleted'), ('USER_ADDED', 'User Added'), ('USER_REMOVED', 'User Removed'), ('DEADLINE_CHANGED', 'Deadline Changed')], default='DEFAULT', max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_list', to='tasks.usernotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ON HOLD', 'On Hold'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ON HOLD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deadline_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deadline')),
                ('groups', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('users', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usernotificationassignment',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_user'),
        ),
    ]
