# Generated by Django 4.1.7 on 2023-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0002_alter_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
