# Generated by Django 4.1.7 on 2023-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
