# Generated by Django 4.1.7 on 2023-06-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskstatus_id_alter_taskstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='on hold', on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus'),
            preserve_default=False,
        ),
    ]
