# Generated by Django 4.1.7 on 2023-06-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
    ]
