# Generated by Django 4.1.7 on 2023-06-04 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_usernotificationstypes_remove_task_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotifications',
            new_name='UserNotification',
        ),
        migrations.RenameModel(
            old_name='UserNotificationsTypes',
            new_name='UserNotificationType',
        ),
    ]
