# Generated by Django 4.1.7 on 2023-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_usernotifications_usernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='type',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.ManyToManyField(related_name='notification_list', to='tasks.usernotificationtype'),
        ),
    ]
