# Generated by Django 4.1.7 on 2023-06-04 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_usernotification_type_usernotification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='is_readed',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='type',
        ),
        migrations.CreateModel(
            name='UserNotificationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to=settings.AUTH_USER_MODEL))),
                ('is_readed', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_list', to='tasks.usernotification')),
            ],
        ),
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.ForeignKey(default='task added', on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to='tasks.usernotificationtype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usernotificationassignment',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_user'),
        ),
    ]
