# Generated by Django 4.1.7 on 2023-06-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_usernotification_is_readed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='on hold', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskstatus'),
        ),
    ]
