# Generated by Django 4.1.7 on 2023-06-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0016_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
