# Generated by Django 4.1.7 on 2023-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_usernotificationassignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OH', 'on hold'), ('IP', 'in progress'), ('CO', 'completed')], default='OH', max_length=2),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('GROUP_ADDED', 'Group Added'), ('GROUP_REMOVED', 'Group Removed'), ('STATUS_CHANGES', 'Status Changes'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_DELETED', 'Task Deleted'), ('USER_ADDED', 'User Added'), ('USER_REMOVED', 'User Removed')], default='DEFAULT', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserNotificationType',
        ),
    ]
